### PR TITLE
Add SQLite DB ENV variables for simpletest.

### PR DESCRIPTION
**Pull request by bhanu951**
Fixes https://github.com/drud/ddev-selenium-standalone-chrome/issues/5

### CODE REVIEW

**Comment by weitzman** [comment]
Can you say a bit about why this is needed? You can override SIMPLETEST_DB in your DDEV config.

**Comment by bhanu951** [comment]
> Can you say a bit about why this is needed? You can override SIMPLETEST_DB in your DDEV config.

Hi @weitzman  

I tried to override `SIMPLETEST_DB` env variable in `config.yml` as below 

```
composer_version: "2"
web_environment:
- SIMPLETEST_DB=sqlite://tmp/sites/simpletest/db.sqlite
nodejs_version: "16"
```

but it has not overrided the value defined in `docker-compose.selenium-chrome.yaml` do you have any suggestion on how to handle it ?

**Comment by weitzman** [comment]
Hmm, IMO that should work. I would have thought that config.yml overrides config copied from a docker-compose file. Maybe @rfay has insight?

If config.yml override is not possible, I think we should only define these vars during our tests and expect users to set them in config.yml. Thats a bit more work and opportunity to struggle but c'est la vie.

**Comment by rfay** [comment]
docker-compose.*.yaml will win, I think.

The environment variables would be better set in a config.selenium-standalone-chrome.yaml I think, would give people more control?

@bhanu951 you should be able to override them with another docker-compose.*.yaml, maybe `docker-compose.z.yaml` or even `docker-compose.override.yaml` which very few people ever use. 

But I do think the better change would be to move these to config.selenium-standalone-chrome.yaml.

**Comment by weitzman** [comment]
Closed in favor of #7

**Pull request closed without merging**
